use crate::routes::{
    AudienceScopeMode, CommandSpec, MessageSemanticType, RelayAuthorizationEntry,
    RelayAuthorizationSpec, RelayContextType, RelayGuardClass, RoutingClass,
};

pub const COMMAND_REGISTRY: &[CommandSpec] = &[
    CommandSpec {
        command_name: "auth",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "auth_login_request",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "auth_register_request",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "auth_identity_request",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_vault_init",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_vault_fetch",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_vault_update_password",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_vault_update_recovery",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_device_vault_fetch",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_device_vault_register",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_endpoint_create",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_register_device",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_approve",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_reject",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_key_wrap",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_key_fetch",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_public_auth",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "device_pairing_auth",
        routing_class: RoutingClass::NoAuth,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "ping",
        routing_class: RoutingClass::GatewayLocal,
        message_type: MessageSemanticType::Technical,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "bootstrap_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "online_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "users_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "mls_key_package_publish",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "mls_key_package_fetch",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_unblock",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contacts_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "notifications_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "notification_ack",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "notification_seen",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "notification_dismiss",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_profiles_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_upload_init",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_upload_chunk",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_upload_finalize",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "audit_timeline_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "audit_timeline_export_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_download_chunk",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_list_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "attachment_delete_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_upload_init",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_upload_payload",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_upload_finalize",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_download",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_list_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_delete_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_share_link_create",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_share_links_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_share_link_revoke",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_share_info_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "user_storage_share_download",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_add",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_accept",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_block",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_profile_upsert",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "contact_profile_delete",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "deadman_config_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "deadman_config_upsert",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_endpoints_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_endpoint_upsert",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_endpoint_delete",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_messages_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_message_delete",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_public_info_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "dropbox_public_submit",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "chat_conversations_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "chat_conversation_open",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "chat_messages_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "group_create",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "group_add",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "group_leave",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "group_membership_accept",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "history_clear",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "identity_profile_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "identity_profile_upsert",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "key_trust_list_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "key_trust_upsert",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "key_trust_delete",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "mls_commit",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "mls_welcome_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "mls_welcome_ack",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "presence_state",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "chat_typing_state",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "signal",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "chat_message_read",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_token_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_create",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_invite",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_join",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_leave",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_media_key",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_mute",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_camera",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_session_token_request",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Query,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_invite",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_join",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_leave",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_mute",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_camera",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "call_media_key",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Signal,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_offer",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: true,
    },
    CommandSpec {
        command_name: "file_transfer_accept",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: true,
    },
    CommandSpec {
        command_name: "file_transfer_reject",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: true,
    },
    CommandSpec {
        command_name: "file_transfer_handshake",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_handshake_ack",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_welcome",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_file_key",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_file_key_ack",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_chunk",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
    CommandSpec {
        command_name: "file_transfer_complete",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: true,
    },
    CommandSpec {
        command_name: "file_transfer_cancel",
        routing_class: RoutingClass::RelayHotpath,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: true,
    },
    CommandSpec {
        command_name: "chat_message_send",
        routing_class: RoutingClass::BackendControl,
        message_type: MessageSemanticType::Command,
        mirror_to_backend: false,
    },
];


const FILE_TRANSFER_OFFER_BOOTSTRAP: RelayAuthorizationSpec = RelayAuthorizationSpec {
    requires_relay_context: false,
    relay_context_type: RelayContextType::FileTransferPeer,
    audience_scope_mode: AudienceScopeMode::FixedPeer,
    guard_class: RelayGuardClass::ContextBoundPeer,
    command_family: "file_transfer",
    operation_key_field: "transfer_id",
};

const FILE_TRANSFER_PEER_CONTEXT: RelayAuthorizationSpec = RelayAuthorizationSpec {
    requires_relay_context: true,
    relay_context_type: RelayContextType::FileTransferPeer,
    audience_scope_mode: AudienceScopeMode::FixedPeer,
    guard_class: RelayGuardClass::ContextBoundPeer,
    command_family: "file_transfer",
    operation_key_field: "transfer_id",
};

pub const RELAY_AUTHORIZATION_REGISTRY: &[RelayAuthorizationEntry] = &[
    RelayAuthorizationEntry {
        command_name: "file_transfer_offer",
        spec: FILE_TRANSFER_OFFER_BOOTSTRAP,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_accept",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_reject",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_handshake",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_handshake_ack",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_welcome",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_file_key",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_file_key_ack",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_chunk",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_complete",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
    RelayAuthorizationEntry {
        command_name: "file_transfer_cancel",
        spec: FILE_TRANSFER_PEER_CONTEXT,
    },
];
